name: robust_calib
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - ffmpeg=4.2.2
  - plyfile=0.8.1
  - pillow=10.2.0
  - pip=23.3.1
  - python=3.8.18
  - pytorch=2.0.0
  - torchaudio=2.0.0
  - torchvision=0.15.0
  - typing_extensions=4.9.0
  - pip:
    - submodules/diff-surfel-rasterization
    - open3d
    - opencv-python
    - scikit-image
    - lpips
    - easydict
    - matplotlib
    - mediapy
    - numpy
    - PyYAML
    - scipy
    - setuptools
    - tqdm
    - trimesh
    - tensorboard